### ISSUE TITLE
Warnings on Mac OS X 10.10

### ISSUE THREAD

**Issue by grizonnetm** [Laadr/otbExternalFastFeaturesSelection#1]
Some warnings are triggered on Mac OS x 10.10:

https://dash.orfeo-toolbox.org/viewBuildError.php?type=1&buildid=263110

Nothing serious but also easy to fix (we can use itkNotUsed macro for some of them)

**Comment by Laadr** [comment]
As you suggested, I used itkNotUsed to declare unused variables. I think it should be alright now. I'm closing the issue but let me if I missed something.
