### ISSUE TITLE
issues in cmake code

### ISSUE THREAD

**Issue by rkanavath** [Laadr/otbExternalFastFeaturesSelection#2]
cmakelists.txt in tests and app is incorrect.
I have to remove this module from package for now.

see link libraries
https://github.com/Laadr/otbFFSforGMM/blob/master/test/CMakeLists.txt
https://github.com/Laadr/otbFFSforGMM/blob/master/app/CMakeLists.txt

**Comment by grizonnetm** [comment]
Hi Rashad,

thanks for the report.

what is exactly the issue in the CMakelists?  I can provide a patch if necessary.

Thanks in advance,

**Comment by rkanavath** [comment]
Hello,

IIRC, the issue was the inconsistency in module name in otb-module.cmake. It was using OTBFastFeaturesSelection in some place and expecting OTBFFSforGMM when calling ${otb-module}-LIBRARIES}
I see this commit which fixed the issue.
https://github.com/Laadr/otbFFSforGMM/commit/69cf8b14fbaf54c4f16a6acdac6f1305f0679d27

To be clear about bug, you have to activate this in package.
https://github.com/orfeotoolbox/OTB/blob/develop/SuperBuild/CMake/External_otb.cmake#L134 and see if there is still failure.

sorry, can't pick up the  exact prob from memory. There was above incosistency, when I filed the bug which apparent points to CMakeLists.txt 's from master

**Comment by grizonnetm** [comment]
Can't find the issue for now in the CMakeLists...

Can we add it back to the packaging?

**Comment by rkanavath** [comment]
yes. you can do this here: https://github.com/orfeotoolbox/OTB/blob/develop/SuperBuild/CMake/External_otb.cmake#L134.

It will affect all packages this way and keep track of what remote modules are enabled in which release.

**Comment by grizonnetm** [comment]
issue reported in otb mantis:

https://bugs.orfeo-toolbox.org/view.php?id=1449
