### ISSUE TITLE
Remove src directory

### ISSUE THREAD

**Issue by gpo-geo** [Laadr/otbExternalFastFeaturesSelection#3]
This module is a template-only module, hence defining a shared library for this module is pointless. The only cxx in the src folder is basically a header test. Please remove the whole 'src' directory.

**Comment by Laadr** [comment]
src directory has been removed. Thanks for the help !

**Comment by gpo-geo** [comment]
Thanks for the reactivity !
I tried to build the module, but there are still minor patches to do.
In your main CMakeLists.txt, the line 3 should be removed (since there is no library in the module).
`set(OTBFFSforGMM_LIBRARIES OTBFFSforGMM)`
In app/CMakeLists.txt, no need to remove the `LINK_LIBRARIES ${${otb-module}_LIBRARIES}`, you should keep them or there is a risk to miss a link library. In the future it may be usefull to make this parameter optional in the macro otb_create_application() ...

**Comment by Laadr** [comment]
Well, obviously I'm a bit clumsy with those CMakeLists... I did what you suggest. Don't hesitate to tell me if there is anything else. Thanks !

**Comment by gpo-geo** [comment]
Great ! I have updated the tag for this remote module in OTB.
