### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by Julien-Osman** [Laadr/otbExternalFastFeaturesSelection#7]
Hi,
This remote module was removed from OTB packaging 3 years ago because it does not compile. See [corresponding issue](https://gitlab.orfeo-toolbox.org/orfeotoolbox/otb/-/issues/1827). Are you planning on fixing it so it can be reintroduced ?
Sincerely.
Julien :)

**Comment by Laadr** [comment]
Hello,
Unfortunately, I am not planning to maintain the project.
Thank you for letting me know about the issue.
Adrien

**Comment by Julien-Osman** [comment]
Thanks for your answer. I will close the issue on OTB's gitlab. If anyone ever fixes this, they will just need to tell us in a comment in the issue.
Regards.
Julien :)
